apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-defaults
spec:
  generators:
    - git:
        repoURL: https://github.com/nicksuckling/home-k8s-gitops.git
        revision: HEAD
        files:
          - path: "charts/cluster-defaults/**/gen-config.json"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ name }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/{{ folderPath }}'
    spec:
      project: cluster-critical
      source:
        path: '{{ folderPath }}'
        targetRevision: HEAD
        repoURL: https://github.com/nicksuckling/home-k8s-gitops.git
        helm:
          valueFiles:
            - values.yaml
            - '{{ valueFile }}'
      destination:
        namespace: '{{ namespace }}'
        name: '{{ cluster }}'
      syncPolicy:
        #  automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
