apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-defaults
spec:
  generators:
    # Generator for apps that shold deploy to all clusters
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
                - appName: prometheus
                  namespace: monitoring
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/nicksuckling/home-k8s-gitops.git
        targetRevision: HEAD
        path: charts/cluster-defaults/{{appName}}/
        helm:
          releaseName: "{{appName}}"
          valueFiles:
            - values.yaml
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
