apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-upgrade
spec:
  generators:
  - list:
      elements:
      - cluster: home
        url: https://kubernetes.default.svc
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-system-upgrade'
    spec:
      project: default
      source:
        repoURL: https://github.com/nicksuckling/home-k8s-gitops.git
        targetRevision: HEAD
        path: system-upgrade/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: system-upgrade
